- hosts: all
  become: true
  tasks:
      # Actualizamos paquetes
    - name: Actualizamos el sistema
      apt: update_cache=yes upgrade=yes
      # Instalar paquetes
    - name: Instalar apache2
      ##Aquí tienes que poner lo necesario para instalar git y apache2
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Instalar git
      ansible.builtin.apt:
        name: git
        state: present
      # Copia un fichero a la máquina remota
    - name: "Copiar fichero a la máquina remota"
      ansible.builtin.copy:
        src: files/foo.conf
        dest: /etc/foo.conf
        owner: root
        group: root
        mode: '0644'
      # Copia un template a un fichero
    - name: "Copiar un tamplate a un fichero de la máquina remota"
      ansible.builtin.template: 
        src: template/index.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0644
    
